// /app/layout.js
import Sidebar from './component/sidebar/sidebar'
import 'bootstrap/dist/css/bootstrap.min.css'

import './global.css' // equivalent to App.css in React

export const metadata = {
	title: 'My Next.js App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<div className="main-wrapper d-flex">
					<Sidebar />
					{children}
				</div>
			</body>
		</html>
	)
}
